# Enable this to get bug fixes and support asap
auto-update: true

worlds:

  # The name of your world that is Earth.
  # This should be the name main world where people work on stuff and make bases.
  earth-name: world

aliens:

  # How often aliens tick in Minecraft ticks - there are 20 ticks in 1 second
  tick-interval: 2

  # Maximum number of aliens per player per world
  max-per-player: 8

  # Chance for a Leech to eat an item
  leech-eat-chance: 50

rockets:
  
  # Messages while rocket is launching. Must have at least 4
  launch-msgs: 
    - Forgetting parachutes
    - Restocking snack bin
    - Aligning planets
    - Igniting sun
    - Inventing funny launch messages
    - Thanking TheBusyBiscuit
    - Faking Moon landings
    - Taking one small step
    - Going Boomer
    - Not going home
    - Calibrating the 'Are We There Yet?'ometer
    - Packing extra duct tape
    - Applying SPF 5000 sunscreen to the engine
    - Pointing the correct end towards space
    - Launching on a wing and a prayer (and a slightly dodgy fuel injector)
