name: Galactifun2
authors: [Seggan, Mooy1, ProfElements, GallowsDove]
description: Space addon for Slimefun
main: io.github.addoncommunity.galactifun.Galactifun2
website: https://github.com/Slimefun-Addon-Community/Galactifun2
version: ${project.version}
api-version: 1.19
depend: [Slimefun]
# This makes ClayTech load before Galactifun, so we can check if it's enabled in onEnable()
softdepend: [ClayTech]
loadbefore: [Multiverse-Core]

commands:
  galactifun:
    description: galactifun main command
    usage: /galactifun <subcommand>
    aliases: [gf, galactic]
